// <auto-generated />
using System;
using Gestion_de_Turnos_Medicos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gestion_de_Turnos_Medicos.Migrations
{
    [DbContext(typeof(dbTurnosMedicos))]
    [Migration("20260904201457_DBInicial")]
    partial class DBInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gestion_de_Turnos_Medicos.DetalleSala", b =>
                {
                    b.Property<int>("IdDetalleSala")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalleSala"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("DescripcionAtencion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdSala")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdDetalleSala");

                    b.HasIndex("IdSala");

                    b.HasIndex("IdUsuario");

                    b.ToTable("DetallesSalas");
                });

            modelBuilder.Entity("Gestion_de_Turnos_Medicos.Especialidad", b =>
                {
                    b.Property<int>("IdEspecialidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEspecialidad"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEspecialidad");

                    b.ToTable("Especialidades");
                });

            modelBuilder.Entity("Gestion_de_Turnos_Medicos.HistoriaClinica", b =>
                {
                    b.Property<int>("IdHistoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHistoria"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("DescripHistoriaClinica")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiagRapido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("int");

                    b.Property<int>("IdTurno")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("RecetaMedicamentos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoTurno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdHistoria");

                    b.HasIndex("IdPaciente");

                    b.HasIndex("IdTurno");

                    b.HasIndex("IdUsuario");

                    b.ToTable("HistoriasClinicas");
                });

            modelBuilder.Entity("Gestion_de_Turnos_Medicos.MedicoEspecialidad", b =>
                {
                    b.Property<int>("IdMedicoEsp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMedicoEsp"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEspecialidad")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdMedicoEsp");

                    b.HasIndex("IdEspecialidad");

                    b.HasIndex("IdUsuario");

                    b.ToTable("MedicosEspecialidades");
                });

            modelBuilder.Entity("Gestion_de_Turnos_Medicos.Paciente", b =>
                {
                    b.Property<int>("IdPaciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPaciente"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObraSocial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPaciente");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("Gestion_de_Turnos_Medicos.Prioridad", b =>
                {
                    b.Property<int>("IdPrioridad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPrioridad"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.HasKey("IdPrioridad");

                    b.ToTable("Prioridades");
                });

            modelBuilder.Entity("Gestion_de_Turnos_Medicos.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.HasKey("IdRol");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Gestion_de_Turnos_Medicos.Sala", b =>
                {
                    b.Property<int>("IdSala")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSala"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("EstadoSala")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreSala")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSala");

                    b.ToTable("Salas");
                });

            modelBuilder.Entity("Gestion_de_Turnos_Medicos.Sintoma", b =>
                {
                    b.Property<int>("IdSintoma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSintoma"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gravedad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSintoma");

                    b.ToTable("Sintomas");
                });

            modelBuilder.Entity("Gestion_de_Turnos_Medicos.Turno", b =>
                {
                    b.Property<int>("IdTurno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTurno"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("Horario")
                        .HasColumnType("time");

                    b.Property<int>("IdEspecialidad")
                        .HasColumnType("int");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("int");

                    b.Property<int>("IdPrioridad")
                        .HasColumnType("int");

                    b.Property<int?>("IdSala")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("NroOrden")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoTurno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTurno");

                    b.HasIndex("IdEspecialidad");

                    b.HasIndex("IdPaciente");

                    b.HasIndex("IdPrioridad");

                    b.HasIndex("IdSala");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Turnos");
                });

            modelBuilder.Entity("Gestion_de_Turnos_Medicos.TurnoSintoma", b =>
                {
                    b.Property<int>("IdTurnoSintoma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTurnoSintoma"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("EstadoActual")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdSintoma")
                        .HasColumnType("int");

                    b.Property<int>("IdTurno")
                        .HasColumnType("int");

                    b.HasKey("IdTurnoSintoma");

                    b.HasIndex("IdSintoma");

                    b.HasIndex("IdTurno");

                    b.ToTable("TurnoSintomas");
                });

            modelBuilder.Entity("Gestion_de_Turnos_Medicos.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NroMatricula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdRol");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Gestion_de_Turnos_Medicos.DetalleSala", b =>
                {
                    b.HasOne("Gestion_de_Turnos_Medicos.Sala", "Sala")
                        .WithMany("DetallesSala")
                        .HasForeignKey("IdSala")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gestion_de_Turnos_Medicos.Usuario", "Usuario")
                        .WithMany("DetallesSala")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sala");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Gestion_de_Turnos_Medicos.HistoriaClinica", b =>
                {
                    b.HasOne("Gestion_de_Turnos_Medicos.Paciente", "Paciente")
                        .WithMany("HistoriasClinicas")
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gestion_de_Turnos_Medicos.Turno", "Turno")
                        .WithMany("HistoriasClinicas")
                        .HasForeignKey("IdTurno")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gestion_de_Turnos_Medicos.Usuario", "Usuario")
                        .WithMany("HistoriasClinicas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Paciente");

                    b.Navigation("Turno");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Gestion_de_Turnos_Medicos.MedicoEspecialidad", b =>
                {
                    b.HasOne("Gestion_de_Turnos_Medicos.Especialidad", "Especialidad")
                        .WithMany("MedicoEspecialidades")
                        .HasForeignKey("IdEspecialidad")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gestion_de_Turnos_Medicos.Usuario", "Usuario")
                        .WithMany("MedicoEspecialidades")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Especialidad");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Gestion_de_Turnos_Medicos.Turno", b =>
                {
                    b.HasOne("Gestion_de_Turnos_Medicos.Especialidad", "Especialidad")
                        .WithMany("Turnos")
                        .HasForeignKey("IdEspecialidad")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gestion_de_Turnos_Medicos.Paciente", "Paciente")
                        .WithMany("Turnos")
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gestion_de_Turnos_Medicos.Prioridad", "Prioridad")
                        .WithMany("Turnos")
                        .HasForeignKey("IdPrioridad")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gestion_de_Turnos_Medicos.Sala", "Sala")
                        .WithMany("Turnos")
                        .HasForeignKey("IdSala");

                    b.HasOne("Gestion_de_Turnos_Medicos.Usuario", "Usuario")
                        .WithMany("Turnos")
                        .HasForeignKey("IdUsuario");

                    b.Navigation("Especialidad");

                    b.Navigation("Paciente");

                    b.Navigation("Prioridad");

                    b.Navigation("Sala");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Gestion_de_Turnos_Medicos.TurnoSintoma", b =>
                {
                    b.HasOne("Gestion_de_Turnos_Medicos.Sintoma", "Sintoma")
                        .WithMany("TurnoSintomas")
                        .HasForeignKey("IdSintoma")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gestion_de_Turnos_Medicos.Turno", "Turno")
                        .WithMany("TurnoSintomas")
                        .HasForeignKey("IdTurno")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sintoma");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("Gestion_de_Turnos_Medicos.Usuario", b =>
                {
                    b.HasOne("Gestion_de_Turnos_Medicos.Rol", "RolNav")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RolNav");
                });

            modelBuilder.Entity("Gestion_de_Turnos_Medicos.Especialidad", b =>
                {
                    b.Navigation("MedicoEspecialidades");

                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("Gestion_de_Turnos_Medicos.Paciente", b =>
                {
                    b.Navigation("HistoriasClinicas");

                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("Gestion_de_Turnos_Medicos.Prioridad", b =>
                {
                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("Gestion_de_Turnos_Medicos.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Gestion_de_Turnos_Medicos.Sala", b =>
                {
                    b.Navigation("DetallesSala");

                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("Gestion_de_Turnos_Medicos.Sintoma", b =>
                {
                    b.Navigation("TurnoSintomas");
                });

            modelBuilder.Entity("Gestion_de_Turnos_Medicos.Turno", b =>
                {
                    b.Navigation("HistoriasClinicas");

                    b.Navigation("TurnoSintomas");
                });

            modelBuilder.Entity("Gestion_de_Turnos_Medicos.Usuario", b =>
                {
                    b.Navigation("DetallesSala");

                    b.Navigation("HistoriasClinicas");

                    b.Navigation("MedicoEspecialidades");

                    b.Navigation("Turnos");
                });
#pragma warning restore 612, 618
        }
    }
}
